# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainbear(object):
    def setupUi(self, mainbear):
        mainbear.setObjectName("mainbear")
        mainbear.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainbear)
        self.centralwidget.setObjectName("centralwidget")
        self.graphWidget = QtQuickWidgets.QQuickWidget(self.centralwidget)
        self.graphWidget.setGeometry(QtCore.QRect(260, 160, 300, 200))
        self.graphWidget.setObjectName("graphWidget")
        mainbear.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainbear)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        mainbear.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainbear)
        self.statusbar.setObjectName("statusbar")
        mainbear.setStatusBar(self.statusbar)

        self.retranslateUi(mainbear)
        QtCore.QMetaObject.connectSlotsByName(mainbear)

    def retranslateUi(self, mainbear):
        _translate = QtCore.QCoreApplication.translate
        mainbear.setWindowTitle(_translate("mainbear", "MainWindow"))
from PyQt5 import QtQuickWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainbear = QtWidgets.QMainWindow()
    ui = Ui_mainbear()
    ui.setupUi(mainbear)
    mainbear.show()
    sys.exit(app.exec_())
